export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="night" lang="fr">
      <head />
      <body>{children}</body>
    </html>
  );
}
